/**
 * Token build script — `npm run tokens:build` (also runs on `prebuild`).
 *
 * Reads design-tokens/tokens.ts and emits:
 *   - src/app/tokens.css   → :root { … } + .dark { … } consumed by Tailwind v4
 *   - mobile/lib/theme.ts  → typed object for the Expo app
 *
 * Both outputs are AUTO-GENERATED. Never hand-edit them.
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  semantic,
  radius,
  dimensions,
  shadows,
  motion,
  zIndex,
  nativeScale,
  primitives,
} from "./tokens.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const BANNER = "/* AUTO-GENERATED by design-tokens/build.ts — do not edit. Run `npm run tokens:build`. */";

// ── src/app/tokens.css ──────────────────────────────────────────────────────

function cssVars(map: Record<string, string>, indent = "  "): string {
  return Object.entries(map)
    .map(([k, v]) => `${indent}--${k}: ${v};`)
    .join("\n");
}

const componentVars: Record<string, string> = {
  radius,
  ...dimensions,
  ...shadows,
  ...motion,
  ...zIndex,
};

const tokensCss = `${BANNER}

:root {
${cssVars(semantic.light)}

  /* component tokens (theme-independent) */
${cssVars(componentVars)}
}

.dark {
${cssVars(semantic.dark)}
}
`;

mkdirSync(join(root, "src/app"), { recursive: true });
writeFileSync(join(root, "src/app/tokens.css"), tokensCss, "utf8");

// ── mobile/lib/theme.ts ─────────────────────────────────────────────────────

function tsObject(map: Record<string, string | number>, indent = "    "): string {
  return Object.entries(map)
    .map(([k, v]) => `${indent}${JSON.stringify(k)}: ${typeof v === "number" ? v : JSON.stringify(v)},`)
    .join("\n");
}

const mobileTheme = `${BANNER}
/* eslint-disable */

export const palette = {
${tsObject(flattenPrimitives(primitives), "  ")}
} as const;

export const theme = {
  light: {
${tsObject(semantic.light)}
  },
  dark: {
${tsObject(semantic.dark)}
  },
  scale: ${JSON.stringify(nativeScale, null, 2).replace(/\n/g, "\n  ")},
} as const;

export type ThemeMode = keyof typeof theme;
export type ThemeColors = typeof theme.light;
`;

mkdirSync(join(root, "mobile/lib"), { recursive: true });
writeFileSync(join(root, "mobile/lib/theme.ts"), mobileTheme, "utf8");

// ── helpers ─────────────────────────────────────────────────────────────────

function flattenPrimitives(obj: Record<string, unknown>, prefix = ""): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(obj)) {
    const key = prefix ? `${prefix}-${k}` : k;
    if (typeof v === "string") out[key] = v;
    else if (v && typeof v === "object") Object.assign(out, flattenPrimitives(v as Record<string, unknown>, key));
  }
  return out;
}

console.log("✓ tokens → src/app/tokens.css, mobile/lib/theme.ts");
